### ISSUE TITLE
Handle case when token timestamp is too old

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-restful-integration#166]
When token timestamp is too old the server returns 500 error. It should return 401 error instead. 

See related issue:
https://github.com/wultra/powerauth-server/issues/331

**Comment by petrdvorak** [comment]
Where is the fix?

**Comment by romanstrobl** [comment]
Fixed in https://github.com/wultra/powerauth-restful-integration/pull/207/files
