### ISSUE TITLE
Deprecate projects powerauth-restful-server-javaee and powerauth-restful-server-spring

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-restful-integration#33]
We should check that all code in these projects is documented and possibly deprecate these projects or at least move them out of powerauth-restful-integration project.

**Comment by petrdvorak** [comment]
The projects currently contain two important pieces of information that are not yet documented:

- Custom activation
- End-to-end Encryption

These, however, change with Crypto 3.0 and we will need to document them again anyway.

**Comment by romanstrobl** [comment]
Closing issue.
