### ISSUE TITLE
Broken link to tutorials

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-restful-integration#522]
Leads to 404 error page.

Fix links:
https://developers.wultra.com/products/mobile-security-suite/develop/tutorials/Authentication-in-Mobile-Apps
https://developers.wultra.com/products/mobile-security-suite/develop/tutorials/Manual-Signature-Verification

to

https://developers.wultra.com/tutorials/posts/Mobile-First-Authentication/
https://developers.wultra.com/tutorials/posts/Manual-Signature-Verification/

**Comment by OliverJanstaWultra** [comment]
Looks good
