### ISSUE TITLE
com.github.kongchen:swagger-maven-plugin can not generate swagger file with /pa/* endpoints

### ISSUE THREAD

**Issue by kvakos** [wultra/powerauth-restful-integration#64]
plugin is not able to find endpoints in spring integration library when they are annotated by @Controller,
but classes annotated by @RestController it finds.

**Comment by petrdvorak** [comment]
Thank you for the report - we will have a look. Just out of curiosity: What plugin do you use?

**Comment by petrdvorak** [comment]
Fixed via #65
